/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./VerifierSimple.types";
import * as _1 from "./VerifierSimple.client";
export namespace contracts {
  export const VerifierSimple = {
    ..._0,
    ..._1
  };
}