/**
* This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { CosmWasmClient } from "@cosmjs/cosmwasm-stargate";
import { Requestor, Uint128, InstantiateMsg, Coin, TimeoutInfo, ExecuteMsg, TaskExecuteMsg, TaskId, Uint64, CustomExecuteMsg, QueryMsg, TaskQueryMsg, CustomQueryMsg, ConfigResponse, TimeoutConfig, ListCompletedResponse, CompletedTaskOverview, ListOpenResponse, OpenTaskOverview, Status, TaskResponse, TaskStatus, TaskStatusResponse } from "./TaskQueue.types";
export interface TaskQueueReadOnlyInterface {
  contractAddress: string;
}
export class TaskQueueQueryClient implements TaskQueueReadOnlyInterface {
  client: CosmWasmClient;
  contractAddress: string;
  constructor(client: CosmWasmClient, contractAddress: string) {
    this.client = client;
    this.contractAddress = contractAddress;
  }
}