/**
 * This file was automatically generated by @cosmwasm/ts-codegen@1.11.1.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export interface InstantiateMsg {
  operator_contract: string;
  required_percentage: number;
}
export type ExecuteMsg = {
  executed_task: {
    result: string;
    task_id: TaskId;
    task_queue_contract: string;
  };
};
export type TaskId = Uint64;
export type Uint64 = string;
export type QueryMsg =
  | {
      // eslint-disable-next-line @typescript-eslint/no-empty-object-type
      config: {};
    }
  | {
      task_info: {
        task_contract: string;
        task_id: TaskId;
      };
    }
  | {
      operator_vote: {
        operator: string;
        task_contract: string;
        task_id: TaskId;
      };
    };
export interface ConfigResponse {
  operator_contract: string;
  required_percentage: number;
}
export type NullableOperatorVoteInfoResponse = OperatorVoteInfoResponse | null;
export type Uint128 = string;
export interface OperatorVoteInfoResponse {
  power: Uint128;
  result: string;
}
export type NullableTaskInfoResponse = TaskInfoResponse | null;
export type TaskStatus = "open" | "completed" | "expired";
export interface TaskInfoResponse {
  power_needed: Uint128;
  status: TaskStatus;
  tallies: TaskTally[];
}
export interface TaskTally {
  power: Uint128;
  result: string;
}
